spring:
  redis:
    # Redis数据库索引（默认为0）
    database: 1
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: Aa123456@?
    # 连接超时时间（毫秒）
    timeout: 10000
    jedis:
      pool:
        # 如果赋值为-1，则表示不限制；如果pool已经分配了maxActive个jedis实例，则此时pool的状态为exhausted(耗尽)。
        max-active: 2000
        # 等待可用连接的最大时间，单位毫秒，默认值为-1，表示永不超时。如果超过等待时间，则直接抛出JedisConnectionException
        max-wait: 1000
        # 连接池中的最大空闲连接，默认值是8。
        max-idle: 100
        #连接池中的最小空闲连接，默认值0。
        min-idle: 50