server:
  port: 8081
spring:
  security:
    user:
      name: admin
      password: 123456
  boot:
    admin:
      client:
        # Spring Boot Admin Server 地址   http://localhost:8080  可自定义
        url:  http://localhost:9999
        instance:
          metadata:
            user.name: ${spring.security.user.name}
            user.password: ${spring.security.user.password}
        username: ${spring.security.user.name}
        password: ${spring.security.user.password}
# 默认情况下，大多数端点都不通过http公开，我们公开了所有端点。对于生产，您应该仔细选择要公开的端点。
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
logging:
  file:
   name: /Users/chenyunxuan/data/project/mc-buy/log/mc-buy.log
  pattern:
    file: '%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx'
